steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'koreichi-maker-api',
         '--region', 'asia-northeast1',
         '--runtime', 'python311',
         '--trigger-http',
         '--gen2',
         '--entry-point', 'koreichi_maker_http',
         '--set-env-vars', 'PROJECT_ID={_PROJECT_ID}']
  dir: './functions'
 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', './appengine/app_mask.yaml']
  dir: './appengine'
 
logsBucket: 'gs://{_BUCKET_NAME}/Log/build'
serviceAccount: 'projects/{_PROJECT_ID}/serviceAccounts/{_SERVICE_ACCOUNT}'
options:
  logging: GCS_ONLY
